# Build Imagemagick Container
FROM {{ dockerUser + "/" + buildImageName + ":" + buildImageVersion }}
LABEL maintainer="{{ dockerUser }} <{{ dockerUserEmail }}>"
USER root

# Install Imagemagick
RUN apk add --no-cache -U imagemagick && \
  rm -rf /var/cache/apk/* && \
  mkdir -p /input /output && \
  chown ${ALPINE_USER}:${ALPINE_USER} -R /input /output

USER ${ALPINE_USER}
WORKDIR /input
VOLUME /input /output
CMD ["convert"]
